#!/usr/bin/python3

from config import Config
from work import Work, Item

config = Config("config.ini", "Directory")

# 获取工作目录
items = []
with open(config.filepath) as f:
    for line in f:
        s = line.strip().split(' ')
        if len(s) > 1:
            items.append(Item(s[0], s[1]))
        else:
            items.append(Item(s[0]))


work = Work(items)

work.backup()

print("Bingo,所有工作已检查完成！")
